# PYTORCH

Basics of Pytorch:

Açık kaynaklı bir kütüphanedir. Facebook tarafından geliştirilmiştir. Yapay Zeka, Derin Öğrenmede kullanılan bir kütüphanedir. Biligsayarda görme, doğal dil işleme gibi alanlarda kullanılabilir. Keras, Numpy gibi özel bir kütüphanedir. 

Pytorch bilimsel haesaplamalar yapmak için kullanılan bir kütüphanedir.(Numpy gibi). Fakat diğerlerinden ayıran özellikleri; GPU power kullanmasıdır. (GPU-->Grafik işlmeci birimidir.) Pytorch biligsayarın ekran kartını kullanır. Zamanda esneklik sağlar ve hızlıdır. 
Debbuging işlemi daha kolaydır. 
Dinamik grafiklerde performansı iyidir. High level ve Low level Api karışımından ortaya çıkmıştır.




# MATRICES

Pytorch da matrislere(array) tensors denir.

3*3 array(matris) ===>   3*3 tensor (3D matrisler tensordur)


Şimdi numpy kütüphanesi ile array tanımlayalım. Ve numpy'dan pytorch kütüphanesine geçiş yapalım.




In [5]:
import numpy as np

# numpy array
array = [[1,2,3],[4,5,6]]
first_array = np.array(array) # 2x3 array
print("Array Type: {}".format(type(first_array))) # type
print("Array Shape: {}".format(np.shape(first_array))) # shape
print(first_array)

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


Şimdi de pytorch array implement edelim.



In [6]:
# import pytorch library
import torch

# pytorch array
tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x00000269C5B19350>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


Allocation çok kullandığımız methodlardan birisindir. Bellekte yer ayırmak için birlerden oluşan bir array yaratmak. Normalde biz bunu numpyda np.ones() şeklinde yapıyorduk. Pytorch da bunu yapmak istersek de "torch.ones()" şeklinde yapabiliyoruz. Memory den yer ayırma işlemidir. 

Numpyda random sayılar yaratmak istersek np.random.rand() işlemi yaparken bunu torch da "torch.rand()" şeklinde yapabiliyoruz.

In [8]:
print("Numpy {}\n".format(np.ones((2,3))))

#pytorch ones

print("Tensor {}\n".format(torch.ones(2,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

Tensor tensor([[1., 1., 1.],
        [1., 1., 1.]])



Numpy ile Pytorch arasında geçişler:

Numpydan Pytorch'a geçiş işlemleri için:

torch.from_numpy()



Torchdan Numpy'a geçiş 

numpy()


In [10]:
#random numpy array

array= np.random.rand(2,2)
print("{}\n".format(type(array),array))


#from numpy to tensor
from_numpy_to_tensor= torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))

#from tensor to numpy

tensor= from_numpy_to_tensor
from_tensor_to_numpy= tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy),from_tensor_to_numpy))

<class 'numpy.ndarray'>

tensor([[0.4090, 0.6657],
        [0.4195, 0.4928]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.40898272 0.66566057]
 [0.41951229 0.4927645 ]]



# Basic Math With Pytorch


Resize: view()

a ve b birer tensordur.

Addition:  torch.add(a,b)====> a+b

Subtraction:  torch.sub(a,b)====> a-b

Element wise division:  torch.div(a,b)====> a/b

Mean:  a.mean()====> Average

Standart Deviation:  std: a.std()

In [12]:
#Create a tensor

tensor= torch.ones(3,3)
print("\n",tensor)


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [13]:
#Resize

print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])



In [14]:
#Addition

print("Addition: {}\n".format(torch.add(tensor,tensor)))

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])



In [15]:
#Subtraction

print("Subtraction: {}\n".format(tensor.sub(tensor)))

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])



In [16]:
#Element wise multiplication

print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor)))

Element wise multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])



In [17]:
#Element wise division

print("Element wise division: {}\n".format(torch.div(tensor,tensor)))

Element wise division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])



In [18]:
#Mean

tensor= torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean()))

Mean: 3.0


In [19]:
#Standart Deviation(std)

print("std: {}".format(tensor.std()))

std: 1.5811388492584229


# VARIABLES

Variables: Gradientler  içerisinde toplayan , biriktiren ve depolayan yapılardır.


Backward Propagation adımında gradientleri hesaplıyorduk. En optimize hyperparametrelerin ayarlamasında kullandığımız adımdı. Bu gradientleri hesapladığımız zaman bu gradient değerlerini elimizde tutabilmek için variable kullanırız.  Vairiable'ın özelliklerinden biri türev aldığımız zaman bu değerleri içinde tutabilmesidir. 

Neural network kurabilmek için ve Backward Propagation yapabilmek için variable kullanırız. 

Gradient değeri Loss fonksiyonunun weightlere göre türevinin alınması. 

Loss fonksiyonu ise cost fonksiyonlarının toplanmasıydı.

Şimdi bir matematiksel örnek yapalım.

Assume we have equation y = x^2

Define x = [2,4] variable

After calculation we find that y = [4,16] (y = x^2)

Recap o equation is that o = (1/2)sum(y) = (1/2)sum(x^2)

deriavative of o = x

Result is equal to x so gradients are [2,4]

Lets implement

Yukarıdaki işlemleri açıklayayım. y=x^2 şeklinde bir denklem vardır. x, 2 ve 4 değerlerini alabilmektedir. y'yi hesaplamak için 2 ve 4'ü yerine koymalıyız. y'yi 4 ve 16 buluruz. o = (1/2)sum(y) = (1/2)sum(x^2) satırında o isimli bir variable tanımlanarak toplama işlemi gerçekleştirilmiştir. Sonrasında o'yu kullanarak x'e göre gradient alınır. Yani o'nun x'e göre türevi alınacaktır.

Bu işlemleri görsel üzerinden ifade edelim:



GRADIENT KULLANIMI :

Aklımızda bir neural network yapısı canlandıralım. Nöronlarımız var ve nöronların arasında bağlantı sağlayabilmek için "weight" değerlerimiz var. Artı olarak bir de "bias" değerlerimiz var. En sonunda bir output değerimiz var ve Output değerimize göre bir "Cost" fonksiyonu hesaplıyoruz. Ardından "tüm costları" toplayıp bir "loss" fonksiyonu elde ediyoruz. Bilindiği üzere "loss" fonksiyonu kurduğumuz modelin performansını gözler önüne serer. Eğer ki "loss" fonksiyonu minimum değerde değilse hyperparametrelerin yeniden ayarlanması (güncellenmesi) gerekir. Hyperparametrelerimiz dediğimiz değişkenler weigtler ve bias değeridir. Backward Propagation adımında "loss" değerini "weight" değerine göre türevinin alınmasıdır. Hesapladığımız bu türev "gradient" değeridir. Tam da bu işlem sonucu değerleri dpolamak için PyTorch kütüphanesinin içinde tanımlı "Variable" adlı veritipini kullanacağız. Değerleri biriktirmiş oluruz. Aslen bunu bir array gibi düşünmek de mümkündür.

In [20]:
# import variable from pytorch library
from torch.autograd import Variable

# define variable
var = Variable(torch.ones(3), requires_grad = True)
var

tensor([1., 1., 1.], requires_grad=True)

tensor([1., 1., 1.], requires_grad=True)
Yukarıdaki from torch.autograd import Variable kod satırı ile variables import edilmiştir.

var = Variable(torch.ones(3), requires_grad = True) satırında ise torch.ones(3) parametresi ile 1'lerden oluşan bir tensör oluşturulmuştur ve Variable'nin içerisine atılmıştır. requires_grad = True parametresi ile gradient bulma işlemi yapılacağı bildirilerek variable'ler ona göre ayarlanmıştır.

Şimdi yukarıda yaptığımız matematiksel örneği kodlayalım.

In [22]:
array = [2,4]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad = True)
y = x**2
print(" y =  ",y)

# recap o equation o = 1/2*sum(y)
o = (1/2)*sum(y)
print(" o =  ",o)

# backward
o.backward() # calculates gradients

print("gradients: ",x.grad)

 y =   tensor([ 4., 16.], grad_fn=<PowBackward0>)
 o =   tensor(10., grad_fn=<MulBackward0>)
gradients:  tensor([2., 4.])
